import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "@/styles/globals.css";
import { ToastContainer } from "react-toastify";
import "@mantine/core/styles.css";
import {
  ColorSchemeScript,
  MantineProvider,
  createTheme,
  mantineHtmlProps,
} from "@mantine/core";
import TanstackQueryProvider from "@/shared/providers/TanstackQuery";
import AuthProvider from "@/shared/providers/AuthProvider";

const lexendDeca = Lexend_Deca({
  variable: "--font-lexend-deca",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  fontFamily: "Lexend Deca, sans-serif",
  headings: { fontFamily: "Lexend Deca, sans-serif" },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${lexendDeca.variable} antialiased`}>
        <ToastContainer />
        <TanstackQueryProvider>
          <MantineProvider theme={theme}>
            <AuthProvider>{children}</AuthProvider>
          </MantineProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
